--- #YAML:1.0
name:                Apache2-AuthEnv
version:             1.3
abstract:            ~
license:             ~
author:              ~
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Apache2::Access:               1
    Apache2::Const:                1
    Apache2::Log:                  1
    Apache2::Module:               1
    Apache2::RequestRec:           1
    Apache2::RequestUtil:          1
    Apache2::ServerUtil:           1
    Carp:                          1
    Data::Dumper:                  1
    mod_perl2:                     2
    ModPerl::Util:                 1
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
